In [2]:
import pandas as pd 

df = pd.read_csv("pythia70m_final_summary.csv")
df = df[df['model_class'] != 'VanillaSAE']

In [3]:
df

,Name,ID,State,User,Group,Job Type,Created,Updated,End Time,Sweep,...,val_online_invalid_ce_loss_recovered,val_online_invalid_ce_loss_recovered_pct,val_online_invalid_clean_loss,val_online_invalid_kl_divergence,val_online_invalid_patched_loss,val_online_invalid_zero_loss,val_online_skipped_batches,val_online_valid_batches,val_online_zero_loss_valid_batches,warmup_factor
0,llm-adaptive_lasso_sweep006-seed1,r7qmjgde,finished,NaN,NaN,NaN,2026-04-22T12:19:04.000Z,2026-04-22T12:53:20.000Z,2026-04-22T12:53:20.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
1,llm-adaptive_lasso_sweep006-seed0,hrv29ppp,finished,NaN,NaN,NaN,2026-04-22T12:17:36.000Z,2026-04-22T12:51:15.000Z,2026-04-22T12:51:15.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
2,llm-adaptive_elastic_net_sweep042-seed1,1e2k4ibt,finished,NaN,NaN,NaN,2026-04-24T06:47:03.000Z,2026-04-24T07:23:34.000Z,2026-04-24T07:23:34.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
3,llm-adaptive_elastic_net_sweep042-seed0,6wgrucsh,finished,NaN,NaN,NaN,2026-04-24T06:47:04.000Z,2026-04-24T07:23:32.000Z,2026-04-24T07:23:32.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
4,llm-adaptive_elastic_net_sweep024-seed0,mfnxe53e,finished,NaN,NaN,NaN,2026-04-23T20:05:46.000Z,2026-04-23T20:40:24.000Z,2026-04-23T20:40:24.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,llm-adaptive_elastic_net_sweep102-seed0,n04egx54,finished,NaN,NaN,NaN,2026-04-25T18:33:34.000Z,2026-04-25T19:09:43.000Z,2026-04-25T19:09:43.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
604,llm-adaptive_elastic_net_sweep102-seed1,vp8wbh5s,finished,NaN,NaN,NaN,2026-04-25T18:37:09.000Z,2026-04-25T19:13:31.000Z,2026-04-25T19:13:31.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
605,llm-adaptive_elastic_net_sweep103-seed2,rulkui02,finished,NaN,NaN,NaN,2026-04-25T17:18:07.000Z,2026-04-25T17:44:33.000Z,2026-04-25T17:44:33.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
606,llm-adaptive_elastic_net_sweep104-seed2,e8u9a838,finished,NaN,NaN,NaN,2026-04-25T17:44:34.000Z,2026-04-25T18:10:36.000Z,2026-04-25T18:10:36.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0
607,llm-adaptive_elastic_net_sweep102-seed2,xh8tngtt,finished,NaN,NaN,NaN,2026-04-25T16:51:36.000Z,2026-04-25T17:18:07.000Z,2026-04-25T17:18:07.000Z,NaN,...,0,0,0,0,0,0,0,50,50,1.0

In [4]:
list(df.columns)

['Name',
 'ID',
 'State',
 'User',
 'Group',
 'Job Type',
 'Created',
 'Updated',
 'End Time',
 'Sweep',
 'Hostname',
 'Description',
 'Commit',
 'GitHub',
 'GPU Count',
 'GPU Type',
 'hp_ema_beta',
 'hp_gamma',
 'hp_ref_k_top_pct',
 'seed',
 'variant_name',
 'hp_lambda_1',
 'hp_lambda_2',
 'activation_normalization',
 'batch_size',
 'd_dict',
 'device',
 'dtype',
 'enable_validation',
 'final_validation_enabled',
 'geometry_log_interval',
 'hook_name',
 'hp_k',
 'hp_weight_max',
 'hp_weight_min',
 'learning_rate',
 'log_interval',
 'max_activations_window',
 'measured_flops_per_step',
 'measured_gflops_per_step',
 'model_class',
 'n_dim',
 'num_steps',
 'online_validation_enabled',
 'tl_model_name',
 'validation_ablation_mode',
 'validation_log_interval',
 'validation_num_batches',
 'warmup_steps',
 'Runtime',
 'Notes',
 'activation_effective_sample_size',
 'active_condition_number',
 'active_max_eigenvalue',
 'dead_features_pct_batch',
 'dead_neurons_pct_window',
 'dictionary_coherence_abs_max',
 'dictionary_coherence_nn/mean',
 'dictionary_coherence_nn/p10',
 'dictionary_coherence_nn/p50',
 'dictionary_coherence_nn/p90',
 'dictionary_coherence_nn/std',
 'dictionary_coherence_nn_max',
 'explained_variance',
 'feature_shrinkage_ratio',
 'feature_utilization_batch/active_feature_pct',
 'feature_utilization_batch/gini',
 'feature_utilization_batch/log10_rate/mean',
 'feature_utilization_batch/log10_rate/p50',
 'feature_utilization_batch/log10_rate/p90',
 'feature_utilization_batch/log10_rate/std',
 'feature_utilization_batch/normalized_entropy',
 'feature_utilization_batch/rate/mean',
 'feature_utilization_batch/rate/p50',
 'feature_utilization_batch/rate/p90',
 'feature_utilization_batch/rate/std',
 'feature_utilization_batch/top10pct_mass_pct',
 'feature_utilization_batch/top1pct_mass_pct',
 'grad_norm/decoder',
 'grad_norm/encoder',
 'grad_norm/global',
 'l0_active_features',
 'l0_vs_l1_ratio',
 'log_active_condition_number',
 'loss',
 'loss_l1',
 'loss_l2',
 'loss_recon',
 'loss_total',
 'mean_max_cosine_similarity',
 'recon_mse',
 'throughput/steps_per_sec',
 'throughput/tokens_per_sec',
 'tokens_seen',
 'update_ratio/decoder',
 'update_ratio/encoder',
 'val_final_adaptive_weight/mean',
 'val_final_adaptive_weight/p10',
 'val_final_adaptive_weight/p50',
 'val_final_adaptive_weight/p90',
 'val_final_adaptive_weight/pinned_max_pct',
 'val_final_adaptive_weight/std',
 'val_final_ce_loss_degradation',
 'val_final_ce_loss_recovered',
 'val_final_ce_loss_recovered_pct',
 'val_final_ce_recovered/mean',
 'val_final_ce_recovered/p10',
 'val_final_ce_recovered/p50',
 'val_final_ce_recovered/p90',
 'val_final_ce_recovered/std',
 'val_final_ce_recovered_pct/mean',
 'val_final_ce_recovered_pct/p10',
 'val_final_ce_recovered_pct/p50',
 'val_final_ce_recovered_pct/p90',
 'val_final_ce_recovered_pct/std',
 'val_final_kl_div',
 'val_final_kl_div/mean',
 'val_final_kl_div/p10',
 'val_final_kl_div/p50',
 'val_final_kl_div/p90',
 'val_final_kl_div/std',
 'val_final_patched_loss',
 'val_online_adaptive_weight/mean',
 'val_online_adaptive_weight/p10',
 'val_online_adaptive_weight/p50',
 'val_online_adaptive_weight/p90',
 'val_online_adaptive_weight/pinned_max_pct',
 'val_online_adaptive_weight/std',
 'val_online_ce_loss_degradation',
 'val_online_ce_loss_recovered',
 'val_online_ce_loss_recovered_pct',
 'val_online_ce_recovered/mean',
 'val_online_ce_recovered/p10',
 'val_online_ce_recovered/p50',
 'val_online_ce_recovered/p90',
 'val_online_ce_recovered/std',
 'val_online_ce_recovered_pct/mean',
 'val_online_ce_recovered_pct/p10',
 'val_online_ce_recovered_pct/p50',
 'val_online_ce_recovered_pct/p90',
 'val_online_ce_recovered_pct/std',
 'val_online_clean_loss',
 'val_online_kl_div',
 'val_online_kl_div/mean',
 'val_online_kl_div/p10',
 'val_online_kl_div/p50',
 'val_online_kl_div/p90',
 'val_online_kl_div/std',
 'val_online_patched_loss',
 'val_online_zero_loss',
 'weight_bimodality_ratio',
 'Tags',
 'active_min_eigenvalue',
 'dead_neuron_recovery_pct',
 'dead_neuron_recovery_rate',
 'dictionary_coherence_overall_mean',
 'dictionary_coherence_subsampled',
 'dictionary_coherence_total_features',
 'dictionary_coherence_used_features',
 'feature_utilization_batch/log10_rate/p10',
 'feature_utilization_batch/rate/p10',
 'interaction_leakage_frobenius',
 'mean_h_j',
 'measured_cumulative_flops',
 'measured_cumulative_tflops',
 'step',
 'total_h_j',
 'val_final_adaptive_weight/pinned_min_pct',
 'val_final_clean_loss',
 'val_final_invalid_ce_loss_degradation',
 'val_final_invalid_ce_loss_recovered',
 'val_final_invalid_ce_loss_recovered_pct',
 'val_final_invalid_clean_loss',
 'val_final_invalid_kl_divergence',
 'val_final_invalid_patched_loss',
 'val_final_invalid_zero_loss',
 'val_final_skipped_batches',
 'val_final_valid_batches',
 'val_final_zero_loss',
 'val_final_zero_loss_valid_batches',
 'val_online_adaptive_weight/pinned_min_pct',
 'val_online_invalid_ce_loss_degradation',
 'val_online_invalid_ce_loss_recovered',
 'val_online_invalid_ce_loss_recovered_pct',
 'val_online_invalid_clean_loss',
 'val_online_invalid_kl_divergence',
 'val_online_invalid_patched_loss',
 'val_online_invalid_zero_loss',
 'val_online_skipped_batches',
 'val_online_valid_batches',
 'val_online_zero_loss_valid_batches',
 'warmup_factor']

In [5]:
best_runs = df.loc[df.groupby('model_class')['l0_active_features'].apply(lambda x: (x - 16).abs().idxmin())]
best_runs[['Name', 'model_class', 'l0_active_features', 'dead_neurons_pct_window', 'explained_variance', 'dictionary_coherence_nn/p90', 'dictionary_coherence_nn_max', 'val_final_patched_loss', 'val_final_kl_div/mean']]

,Name,model_class,l0_active_features,dead_neurons_pct_window,explained_variance,dictionary_coherence_nn/p90,dictionary_coherence_nn_max,val_final_patched_loss,val_final_kl_div/mean
357,llm-adaptive_elastic_net_sweep070-seed1,AdaptiveElasticNetSAE,15.942261,2.026367,0.491420,0.572298,0.971344,12.534615,7.179044
411,llm-adaptive_lasso_sweep031-seed1,AdaptiveLassoSAE,16.106079,28.369141,0.632692,0.650563,0.914638,12.724414,8.260100
287,llm-elastic_net_sweep001-seed2,ElasticNetSAE,12.145996,1.171875,0.399246,0.476438,0.883393,11.572894,6.652521
40,llm-topk_baseline_sweep001-seed0,TopKSAE,16.000000,2.685547,0.680791,0.318941,0.985522,7.952548,2.832720

In [6]:
best_runs = df  .loc[df.groupby('model_class')['l0_active_features'].apply(lambda x: (x - 32).abs().idxmin())]
best_runs[['Name', 'model_class', 'l0_active_features', 'dead_neurons_pct_window', 'explained_variance', 'dictionary_coherence_nn/p90', 'dictionary_coherence_nn_max', 'val_final_patched_loss', 'val_final_kl_div/mean']]

,Name,model_class,l0_active_features,dead_neurons_pct_window,explained_variance,dictionary_coherence_nn/p90,dictionary_coherence_nn_max,val_final_patched_loss,val_final_kl_div/mean
375,llm-adaptive_elastic_net_sweep063-seed0,AdaptiveElasticNetSAE,32.117676,0.659180,0.557677,0.612364,0.993545,12.042908,7.147965
369,llm-adaptive_lasso_sweep025-seed0,AdaptiveLassoSAE,31.165283,3.637695,0.710663,0.596613,0.898263,15.368353,11.129183
328,llm-elastic_net_sweep006-seed1,ElasticNetSAE,30.177856,0.903320,0.627374,0.525596,0.997747,11.515702,6.536487
47,llm-topk_baseline_sweep002-seed0,TopKSAE,32.000000,15.332031,0.759273,0.327144,0.989909,7.041262,1.987565

In [7]:
best_runs = df  .loc[df.groupby('model_class')['l0_active_features'].apply(lambda x: (x - 128).abs().idxmin())]
best_runs[['Name', 'model_class', 'l0_active_features', 'dead_neurons_pct_window', 'explained_variance', 'dictionary_coherence_nn/p90', 'dictionary_coherence_nn_max', 'val_final_patched_loss', 'val_final_kl_div/mean']]

,Name,model_class,l0_active_features,dead_neurons_pct_window,explained_variance,dictionary_coherence_nn/p90,dictionary_coherence_nn_max,val_final_patched_loss,val_final_kl_div/mean
359,llm-adaptive_elastic_net_sweep136-seed2,AdaptiveElasticNetSAE,127.976440,1.806641,0.856133,0.574944,0.932942,8.089263,3.273120
270,llm-adaptive_lasso_sweep027-seed0,AdaptiveLassoSAE,125.693115,0.341797,0.867123,0.464575,0.681259,6.343579,1.899326
565,llm-elastic_net_sweep004-seed1,ElasticNetSAE,70.129517,0.708008,0.560829,0.870149,0.997806,17.591210,12.508534
214,llm-topk_baseline_sweep004-seed0,TopKSAE,128.000000,12.207031,0.904068,0.436081,0.996459,5.788738,0.786227

In [8]:
import pandas as pd

def get_formatted_table(df, target_l0):
    # 1. Find the average L0 for each variant (hyperparameter config) across its 3 seeds
    variant_l0 = df.groupby(['model_class', 'variant_name'])['l0_active_features'].mean().reset_index()
    
    # 2. For each architecture, find the variant closest to the target L0
    best_idx = variant_l0.groupby('model_class')['l0_active_features'].apply(
        lambda x: (x - target_l0).abs().idxmin()
    )
    best_variants = variant_l0.loc[best_idx, ['model_class', 'variant_name']]
    
    # 3. Filter the original dataframe to ONLY include the 3 seeds of those best variants
    best_runs = df.merge(best_variants, on=['model_class', 'variant_name'])
    
    # 4. Helper function to format the numbers as "mean [min, max]"
    def format_stat(x, is_pct=False, decimals=3):
        val_center = x.mean() # Change to x.median() here if you want median instead
        val_min = x.min()
        val_max = x.max()
        
        if is_pct:
            return f"{val_center:.1f}% [{val_min:.1f}, {val_max:.1f}]"
        else:
            return f"{val_center:.{decimals}f} [{val_min:.{decimals}f}, {val_max:.{decimals}f}]"

    # 5. Group by model_class and apply the formatting
    records = []
    for model_class, group in best_runs.groupby('model_class'):
        records.append({
            'Name' : group['Name'].iloc[0],
            'Target L0': f"~ {target_l0}",
            'Architecture': model_class,
            'Achieved L0': format_stat(group['l0_active_features'], decimals=1),
            'Dead Neurons.': format_stat(group['dead_neurons_pct_window'], is_pct=True),
            'Expl. Var.': format_stat(group['explained_variance'], decimals=3),
            'p50 Coh.': format_stat(group['dictionary_coherence_nn/p50'], decimals=3),
            'p90 Coh.': format_stat(group['dictionary_coherence_nn/p90'], decimals=3),
            'Max Coh.': format_stat(group['dictionary_coherence_abs_max'], decimals=3),
            'Shrinkage': format_stat(group['feature_shrinkage_ratio'], decimals=3),
            'Norm. Ent.': format_stat(group['feature_utilization_batch/normalized_entropy'], decimals=3),
            'Top 10 mass;': format_stat(group['feature_utilization_batch/top10pct_mass_pct'], decimals=3),
            'Val final patched loss': format_stat(group['val_final_patched_loss'], decimals=3),
            'Val final KL div.': format_stat(group['val_final_kl_div/mean'], decimals=3),
        })

        
    return pd.DataFrame(records)


table_16 = get_formatted_table(df, target_l0=16)
table_32 = get_formatted_table(df, target_l0=32)
table_128 = get_formatted_table(df, target_l0=128)

print("Table for Target L0 = 16")
print(table_16.to_string(index=False))

print("\nTable for Target L0 = 32")
print(table_32.to_string(index=False))

print("\nTable for Target L0 = 128")
print(table_128.to_string(index=False))

Table for Target L0 = 16
                                   Name Target L0          Architecture       Achieved L0      Dead Neurons.           Expl. Var.             p50 Coh.             p90 Coh.             Max Coh.            Shrinkage           Norm. Ent.            Top 10 mass;  Val final patched loss    Val final KL div.
llm-adaptive_elastic_net_sweep087-seed1      ~ 16 AdaptiveElasticNetSAE 15.9 [14.6, 18.1]    1.4% [0.7, 2.1] 0.610 [0.599, 0.627] 0.204 [0.200, 0.206] 0.446 [0.437, 0.463] 0.911 [0.892, 0.928] 0.690 [0.680, 0.701] 0.631 [0.584, 0.717] 94.781 [86.227, 99.102] 11.419 [11.069, 11.887] 6.648 [6.563, 6.744]
      llm-adaptive_lasso_sweep031-seed0      ~ 16      AdaptiveLassoSAE 16.1 [15.5, 16.6] 20.2% [11.2, 28.4] 0.639 [0.631, 0.653] 0.279 [0.200, 0.426] 0.662 [0.646, 0.690] 0.917 [0.907, 0.930] 0.728 [0.726, 0.730] 0.506 [0.498, 0.519] 93.057 [91.146, 94.251] 12.016 [10.100, 13.225] 7.347 [5.050, 8.730]
         llm-elastic_net_sweep001-seed1      ~ 16         ElasticNetSAE 11.1 [10.5, 12.1]    0.9% [0.7, 1.2] 0.392 [0.386, 0.399] 0.291 [0.286, 0.301] 0.452 [0.436, 0.476] 0.935 [0.883, 0.975] 0.554 [0.547, 0.567] 0.676 [0.658, 0.712] 98.746 [96.278, 99.994] 11.626 [11.573, 11.658] 6.081 [5.774, 6.653]
       llm-topk_baseline_sweep001-seed0      ~ 16               TopKSAE 16.0 [16.0, 16.0]    2.3% [2.0, 2.7] 0.680 [0.679, 0.681] 0.256 [0.253, 0.262] 0.326 [0.319, 0.334] 0.986 [0.986, 0.987] 0.859 [0.855, 0.864] 0.664 [0.663, 0.664] 97.417 [97.290, 97.589]    7.945 [7.920, 7.963] 2.822 [2.802, 2.833]

Table for Target L0 = 32
                                   Name Target L0          Architecture       Achieved L0      Dead Neurons.           Expl. Var.             p50 Coh.             p90 Coh.             Max Coh.            Shrinkage           Norm. Ent.            Top 10 mass;  Val final patched loss     Val final KL div.
llm-adaptive_elastic_net_sweep063-seed1      ~ 32 AdaptiveElasticNetSAE 33.7 [31.3, 37.6]    1.3% [0.6, 2.6] 0.571 [0.553, 0.602] 0.236 [0.212, 0.282] 0.619 [0.605, 0.638] 0.994 [0.993, 0.996] 0.641 [0.630, 0.660] 0.745 [0.719, 0.795] 84.634 [73.224, 90.383] 12.197 [12.043, 12.377]  6.950 [6.471, 7.232]
      llm-adaptive_lasso_sweep025-seed1      ~ 32      AdaptiveLassoSAE 32.2 [30.8, 34.5]    3.5% [2.8, 4.1] 0.717 [0.709, 0.730] 0.260 [0.221, 0.338] 0.607 [0.591, 0.634] 0.971 [0.970, 0.971] 0.795 [0.788, 0.800] 0.584 [0.582, 0.586] 98.396 [98.339, 98.464]  13.008 [9.151, 15.368] 8.507 [4.091, 11.129]
         llm-elastic_net_sweep006-seed0      ~ 32         ElasticNetSAE 33.4 [30.1, 39.9]    1.5% [0.6, 2.9] 0.625 [0.618, 0.630] 0.197 [0.192, 0.209] 0.532 [0.519, 0.551] 0.975 [0.931, 0.998] 0.712 [0.691, 0.750] 0.796 [0.793, 0.802] 71.720 [69.631, 72.895] 11.746 [11.455, 12.267]  6.558 [6.482, 6.656]
       llm-topk_baseline_sweep002-seed0      ~ 32               TopKSAE 32.0 [32.0, 32.0] 13.9% [12.8, 15.3] 0.760 [0.759, 0.760] 0.225 [0.225, 0.226] 0.329 [0.327, 0.330] 0.989 [0.989, 0.990] 0.881 [0.881, 0.882] 0.715 [0.714, 0.716] 90.276 [90.075, 90.515]    7.087 [7.041, 7.141]  2.038 [1.988, 2.087]

Table for Target L0 = 128
                                   Name Target L0          Architecture          Achieved L0     Dead Neurons.           Expl. Var.             p50 Coh.             p90 Coh.             Max Coh.            Shrinkage           Norm. Ent.            Top 10 mass;  Val final patched loss      Val final KL div.
llm-adaptive_elastic_net_sweep136-seed0     ~ 128 AdaptiveElasticNetSAE 127.5 [127.3, 128.0]   3.1% [1.8, 5.2] 0.854 [0.853, 0.856] 0.325 [0.313, 0.350] 0.540 [0.520, 0.575] 0.938 [0.931, 0.951] 0.876 [0.868, 0.881] 0.899 [0.893, 0.909] 48.207 [44.550, 50.117]    7.461 [6.866, 8.089]   2.815 [2.399, 3.273]
      llm-adaptive_lasso_sweep027-seed0     ~ 128      AdaptiveLassoSAE 124.4 [122.3, 125.7]   0.6% [0.3, 1.1] 0.873 [0.867, 0.882] 0.300 [0.283, 0.333] 0.495 [0.465, 0.550] 0.988 [0.985, 0.990] 0.885 [0.874, 0.907] 0.893 [0.877, 0.901] 50.545 [47.945, 55.433]    6.773 [6.160, 7.817]   2.185 [1.749, 2.905]
         llm-elastic_net_sweep004-seed1     ~ 128         ElasticNetSAE    67.9 [64.9, 70.1]   0.6% [0.3, 0.9] 0.544 [0.517, 0.561] 0.595 [0.575, 0.628] 0.884 [0.870, 0.897] 0.999 [0.998, 0.999] 0.613 [0.605, 0.617] 0.843 [0.829, 0.866] 60.028 [52.506, 64.706] 16.606 [13.255, 18.971] 11.011 [7.143, 13.380]
       llm-topk_baseline_sweep004-seed0     ~ 128               TopKSAE 128.0 [128.0, 128.0] 12.0% [9.3, 14.5] 0.904 [0.904, 0.905] 0.231 [0.228, 0.234] 0.449 [0.436, 0.463] 0.997 [0.996, 0.997] 0.954 [0.953, 0.955] 0.755 [0.754, 0.756] 86.139 [85.834, 86.444]    5.790 [5.769, 5.812]   0.774 [0.749, 0.786]