In [1]:
import pandas as pd 

df = pd.read_csv("spiked_v2_final_summary.csv")

In [ ]:
# df[(df['model_class'] == 'VanillaSAE') & (df['rho'] == 0)][['l0_active_features', 'dead_neurons_pct', 'explained_variance']]

     l0_active_features  dead_neurons_pct  explained_variance
233          325.316406          0.000000            0.972487
234           51.308594          0.000000            0.884206
235           21.324219          1.660156            0.723210
236            0.500000         13.867188            0.016295

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Name                                       237 non-null    object
 1   l0_active_features                         237 non-null    float64
 2   State                                      237 non-null    object
 3   Notes                                      237 non-null    object
 4   User                                       0 non-null      float64
 5   Tags                                       237 non-null    object
 6   Created                                    237 non-null    object
 7   Runtime                                    237 non-null    int64
 8   Sweep                                      0 non-null      float64
 9   batch_size                                 237 non-null    int64
 10  device                                     237 non-null    object
 11  dict_active_condition_number_p95           237 non-null    float64
 12  dict_expected_active_condition_number      237 non-null    float64
 13  dict_expected_active_condition_number_std  237 non-null    float64
 14  dict_expected_active_min_eig               237 non-null    float64
 15  dict_expected_active_min_eig_std           237 non-null    float64
 16  dict_expected_irc_exact                    237 non-null    float64
 17  dict_expected_irc_uniform                  237 non-null    float64
 18  dict_expected_signal_ceiling_l_inf         237 non-null    float64
 19  dict_max_abs_offdiag                       237 non-null    float64
 20  dict_mean_abs_offdiag                      237 non-null    float64
 21  dict_singular_active_block_pct             237 non-null    int64
 22  dtype                                      237 non-null    object
 23  learning_rate                              237 non-null    float64
 24  log_interval                               237 non-null    int64
 25  max_activations_window                     237 non-null    int64
 26  measured_flops_per_step                    237 non-null    int64
 27  measured_gflops_per_step                   237 non-null    float64
 28  model_class                                237 non-null    object
 29  model_type                                 237 non-null    object
 30  num_steps                                  237 non-null    int64
 31  rho                                        237 non-null    float64
 32  seed                                       237 non-null    int64
 33  warmup_steps                               237 non-null    int64
 34  activation_effective_sample_size           192 non-null    float64
 35  active_condition_number                    236 non-null    float64
 36  active_max_eigenvalue                      236 non-null    float64
 37  active_min_eigenvalue                      236 non-null    float64
 38  code_recovery_l2                           237 non-null    float64
 39  code_recovery_mse                          237 non-null    float64
 40  dead_neuron_recovery_pct                   237 non-null    float64
 41  dead_neuron_recovery_rate                  237 non-null    float64
 42  dead_neurons_pct                           237 non-null    float64
 43  dictionary_coherence_abs_max               237 non-null    float64
 44  dictionary_coherence_nn/mean               237 non-null    float64
 45  dictionary_coherence_nn/p10                237 non-null    float64
 46  dictionary_coherence_nn/p50                237 non-null    float64
 47  dictionary_coherence_nn/p90                237 non-null    float64
 48  dictionary_coherence_nn/std                237 non-null    float64
 49  dictionary_coherence_nn_max                237 non-null    float64
 50  dictionary_coherence_overall_mean          237 non-null    float64
 51  dictionary_coherence_subsampled            237 non-null    int64
 52  dictionary_coherence_total_features        237 non-null    int64
 53  dictionary_coherence_used_features         237 non-null    int64
 54  dictionary_error_cosine                    237 non-null    float64
 55  dictionary_error_frobenius                 237 non-null    float64
 56  explained_variance                         237 non-null    float64
 57  feature_shrinkage_ratio                    237 non-null    float64
 58  interaction_leakage_frobenius              237 non-null    float64
 59  l0_vs_l1_ratio                             237 non-null    float64
 60  loss                                       237 non-null    float64
 61  loss_l1                                    237 non-null    float64
 62  loss_l2                                    178 non-null    float64
 63  loss_recon                                 237 non-null    float64
 64  loss_total                                 237 non-null    float64
 65  mean_h_j                                   237 non-null    float64
 66  mean_max_cosine_similarity                 237 non-null    float64
 67  measured_cumulative_flops                  237 non-null    int64
 68  measured_cumulative_tflops                 237 non-null    float64
 69  shadowed_ids                               237 non-null    object
 70  shadowed_scores                            237 non-null    object
 71  step                                       237 non-null    int64
 72  support_f1_score                           237 non-null    float64
 73  support_jaccard_similarity                 237 non-null    float64
 74  support_precision                          237 non-null    float64
 75  support_recall                             237 non-null    float64
 76  total_h_j                                  237 non-null    float64
 77  warmup_factor                              202 non-null    float64
 78  weight_bimodality_ratio                    192 non-null    float64
dtypes: float64(54), int64(14), object(11)
memory usage: 146.4+ KB

In [93]:
df_filtered = df[(df['l0_active_features'] >= 2) & (df['rho'] == 0.9)].copy()

In [101]:
best_runs = df_filtered.loc[df_filtered.groupby('model_class')['l0_active_features'].apply(lambda x: (x - 16).abs().idxmin())]
best_runs[['model_class', 'l0_active_features', 'dead_neurons_pct', 'explained_variance', 'code_recovery_l2', 'dictionary_error_frobenius', 'support_f1_score', 'support_precision', 'support_recall']]

,model_class,l0_active_features,dead_neurons_pct,explained_variance,code_recovery_l2,dictionary_error_frobenius,support_f1_score,support_precision,support_recall
19,AdaptiveElasticNetSAE,18.402344,43.359375,0.672843,7.823472,40.602325,0.399682,0.373594,0.429687
91,AdaptiveLassoSAE,17.085938,51.464844,0.645039,8.118853,41.376663,0.344746,0.333791,0.356445
115,ElasticNetSAE,13.351562,81.542969,0.328889,8.308116,44.394165,0.031141,0.034231,0.028564
12,TopKSAE,14.941406,98.144531,0.449735,14.311655,44.348236,0.014644,0.015163,0.014160
7,VanillaSAE,17.265625,67.675781,0.533119,8.148271,42.563606,0.192343,0.185294,0.199951